version: '3.8'

services:
  web:
    image: php:8.1-apache
    container_name: bga_web
    ports:
      - "8080:80"
    volumes:
      - ./bga-studio:/var/www/html
      - ./bga-njet:/var/www/html/games/njet
    environment:
      - APACHE_DOCUMENT_ROOT=/var/www/html
    depends_on:
      - db
    command: >
      bash -c "
        apt-get update &&
        apt-get install -y libpng-dev libjpeg-dev libfreetype6-dev zip unzip git &&
        docker-php-ext-configure gd --with-freetype --with-jpeg &&
        docker-php-ext-install gd mysqli pdo pdo_mysql &&
        a2enmod rewrite &&
        apache2-foreground
      "

  db:
    image: mysql:8.0
    container_name: bga_mysql
    environment:
      MYSQL_ROOT_PASSWORD: bga_root_password
      MYSQL_DATABASE: bga_njet
      MYSQL_USER: bga_user
      MYSQL_PASSWORD: bga_password
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./bga-njet/dbmodel.sql:/docker-entrypoint-initdb.d/init.sql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: bga_phpmyadmin
    environment:
      PMA_HOST: db
      PMA_USER: root
      PMA_PASSWORD: bga_root_password
    ports:
      - "8081:80"
    depends_on:
      - db

volumes:
  mysql_data: